import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navpar from "./_componets/navpar/navpar";
import Footer from "./_componets/footer/footer";
import {Toaster}  from "react-hot-toast";
import NextauthProvider from "./providers/nextauthProvider";
import Providers from "./providers/react-query-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <NextauthProvider>
              <Toaster/>
              <Navpar /> 
                <div className="container mx-auto max-w-7xl">
                  {children}
                </div>
              <Footer />
          </NextauthProvider>
        </Providers>
      </body>
    </html>
  );
}
